version: '3.8'

services:
  search-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/taquangtu/findx:master
    ports:
      - "50051:50051"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
  db:
    image: postgres:17.4
    restart: always
    shm_size: 128mb
    volumes:
      - /volumes/postgres_findx:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - postgres.env
