version: '3.9'

services:
  findx:
    build:
      context: .
      dockerfile: Dockerfile
    image: findxai:dev
    ports:
      - "50051:50051"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16.1
    restart: always
    shm_size: 128mb
    volumes:
      - /home/$USER/docker/volumes/postgres_findx:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: verylongandhardpassword
      POSTGRES_USER: pg
      POSTGRES_DB: findx

  redis:
    image: redis:7.4.2
    ports:
      - 6379:6379
