// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/search.proto

package searchsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	C2Coff           string                 `protobuf:"bytes,1,opt,name=c2coff,proto3" json:"c2coff,omitempty"`
	Cr               string                 `protobuf:"bytes,2,opt,name=cr,proto3" json:"cr,omitempty"`
	DateRestrict     string                 `protobuf:"bytes,3,opt,name=date_restrict,json=dateRestrict,proto3" json:"date_restrict,omitempty"`
	ExactTerms       string                 `protobuf:"bytes,4,opt,name=exact_terms,json=exactTerms,proto3" json:"exact_terms,omitempty"`
	ExcludeTerms     string                 `protobuf:"bytes,5,opt,name=exclude_terms,json=excludeTerms,proto3" json:"exclude_terms,omitempty"`
	FileType         string                 `protobuf:"bytes,6,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Filter           string                 `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	Gl               string                 `protobuf:"bytes,8,opt,name=gl,proto3" json:"gl,omitempty"`
	HighRange        string                 `protobuf:"bytes,9,opt,name=high_range,json=highRange,proto3" json:"high_range,omitempty"`
	Hl               string                 `protobuf:"bytes,10,opt,name=hl,proto3" json:"hl,omitempty"`
	Hq               string                 `protobuf:"bytes,11,opt,name=hq,proto3" json:"hq,omitempty"`
	ImgColorType     string                 `protobuf:"bytes,12,opt,name=img_color_type,json=imgColorType,proto3" json:"img_color_type,omitempty"`
	ImgDominantColor string                 `protobuf:"bytes,13,opt,name=img_dominant_color,json=imgDominantColor,proto3" json:"img_dominant_color,omitempty"`
	ImgSize          string                 `protobuf:"bytes,14,opt,name=img_size,json=imgSize,proto3" json:"img_size,omitempty"`
	ImgType          string                 `protobuf:"bytes,15,opt,name=img_type,json=imgType,proto3" json:"img_type,omitempty"`
	Language         string                 `protobuf:"bytes,16,opt,name=language,proto3" json:"language,omitempty"`
	LinkSite         string                 `protobuf:"bytes,17,opt,name=link_site,json=linkSite,proto3" json:"link_site,omitempty"`
	LowRange         string                 `protobuf:"bytes,18,opt,name=low_range,json=lowRange,proto3" json:"low_range,omitempty"`
	Lr               string                 `protobuf:"bytes,19,opt,name=lr,proto3" json:"lr,omitempty"`
	Num              int32                  `protobuf:"varint,20,opt,name=num,proto3" json:"num,omitempty"`
	OrTerms          string                 `protobuf:"bytes,21,opt,name=or_terms,json=orTerms,proto3" json:"or_terms,omitempty"`
	Q                string                 `protobuf:"bytes,22,opt,name=q,proto3" json:"q,omitempty"`
	Rights           string                 `protobuf:"bytes,23,opt,name=rights,proto3" json:"rights,omitempty"`
	Safe             string                 `protobuf:"bytes,24,opt,name=safe,proto3" json:"safe,omitempty"`
	SearchType       string                 `protobuf:"bytes,25,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"`
	SiteSearch       string                 `protobuf:"bytes,26,opt,name=site_search,json=siteSearch,proto3" json:"site_search,omitempty"`
	SiteSearchFilter string                 `protobuf:"bytes,27,opt,name=site_search_filter,json=siteSearchFilter,proto3" json:"site_search_filter,omitempty"`
	Sort             string                 `protobuf:"bytes,28,opt,name=sort,proto3" json:"sort,omitempty"`
	Start            int32                  `protobuf:"varint,29,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetC2Coff() string {
	if x != nil {
		return x.C2Coff
	}
	return ""
}

func (x *SearchRequest) GetCr() string {
	if x != nil {
		return x.Cr
	}
	return ""
}

func (x *SearchRequest) GetDateRestrict() string {
	if x != nil {
		return x.DateRestrict
	}
	return ""
}

func (x *SearchRequest) GetExactTerms() string {
	if x != nil {
		return x.ExactTerms
	}
	return ""
}

func (x *SearchRequest) GetExcludeTerms() string {
	if x != nil {
		return x.ExcludeTerms
	}
	return ""
}

func (x *SearchRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *SearchRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SearchRequest) GetGl() string {
	if x != nil {
		return x.Gl
	}
	return ""
}

func (x *SearchRequest) GetHighRange() string {
	if x != nil {
		return x.HighRange
	}
	return ""
}

func (x *SearchRequest) GetHl() string {
	if x != nil {
		return x.Hl
	}
	return ""
}

func (x *SearchRequest) GetHq() string {
	if x != nil {
		return x.Hq
	}
	return ""
}

func (x *SearchRequest) GetImgColorType() string {
	if x != nil {
		return x.ImgColorType
	}
	return ""
}

func (x *SearchRequest) GetImgDominantColor() string {
	if x != nil {
		return x.ImgDominantColor
	}
	return ""
}

func (x *SearchRequest) GetImgSize() string {
	if x != nil {
		return x.ImgSize
	}
	return ""
}

func (x *SearchRequest) GetImgType() string {
	if x != nil {
		return x.ImgType
	}
	return ""
}

func (x *SearchRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SearchRequest) GetLinkSite() string {
	if x != nil {
		return x.LinkSite
	}
	return ""
}

func (x *SearchRequest) GetLowRange() string {
	if x != nil {
		return x.LowRange
	}
	return ""
}

func (x *SearchRequest) GetLr() string {
	if x != nil {
		return x.Lr
	}
	return ""
}

func (x *SearchRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SearchRequest) GetOrTerms() string {
	if x != nil {
		return x.OrTerms
	}
	return ""
}

func (x *SearchRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchRequest) GetRights() string {
	if x != nil {
		return x.Rights
	}
	return ""
}

func (x *SearchRequest) GetSafe() string {
	if x != nil {
		return x.Safe
	}
	return ""
}

func (x *SearchRequest) GetSearchType() string {
	if x != nil {
		return x.SearchType
	}
	return ""
}

func (x *SearchRequest) GetSiteSearch() string {
	if x != nil {
		return x.SiteSearch
	}
	return ""
}

func (x *SearchRequest) GetSiteSearchFilter() string {
	if x != nil {
		return x.SiteSearchFilter
	}
	return ""
}

func (x *SearchRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *SearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeactivateKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []string               `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	ForceDelete   bool                   `protobuf:"varint,2,opt,name=force_delete,json=forceDelete,proto3" json:"force_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateKeysRequest) Reset() {
	*x = DeactivateKeysRequest{}
	mi := &file_api_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateKeysRequest) ProtoMessage() {}

func (x *DeactivateKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateKeysRequest.ProtoReflect.Descriptor instead.
func (*DeactivateKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{3}
}

func (x *DeactivateKeysRequest) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *DeactivateKeysRequest) GetForceDelete() bool {
	if x != nil {
		return x.ForceDelete
	}
	return false
}

type DeactivateKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateKeysResponse) Reset() {
	*x = DeactivateKeysResponse{}
	mi := &file_api_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateKeysResponse) ProtoMessage() {}

func (x *DeactivateKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateKeysResponse.ProtoReflect.Descriptor instead.
func (*DeactivateKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{4}
}

type ActivateKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []string               `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateKeysRequest) Reset() {
	*x = ActivateKeysRequest{}
	mi := &file_api_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKeysRequest) ProtoMessage() {}

func (x *ActivateKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKeysRequest.ProtoReflect.Descriptor instead.
func (*ActivateKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{5}
}

func (x *ActivateKeysRequest) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type ActivateKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateKeysResponse) Reset() {
	*x = ActivateKeysResponse{}
	mi := &file_api_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKeysResponse) ProtoMessage() {}

func (x *ActivateKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKeysResponse.ProtoReflect.Descriptor instead.
func (*ActivateKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{6}
}

type KeyInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey         string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SearchEngineId string                 `protobuf:"bytes,4,opt,name=search_engine_id,json=searchEngineId,proto3" json:"search_engine_id,omitempty"`
	IsActive       bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DailyQueries   int32                  `protobuf:"varint,6,opt,name=daily_queries,json=dailyQueries,proto3" json:"daily_queries,omitempty"`
	StatusCode     int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	mi := &file_api_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{7}
}

func (x *KeyInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KeyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyInfo) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *KeyInfo) GetSearchEngineId() string {
	if x != nil {
		return x.SearchEngineId
	}
	return ""
}

func (x *KeyInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *KeyInfo) GetDailyQueries() int32 {
	if x != nil {
		return x.DailyQueries
	}
	return 0
}

func (x *KeyInfo) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *KeyInfo) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *KeyInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KeyInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*KeyInfo             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeysRequest) Reset() {
	*x = AddKeysRequest{}
	mi := &file_api_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeysRequest) ProtoMessage() {}

func (x *AddKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeysRequest.ProtoReflect.Descriptor instead.
func (*AddKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{8}
}

func (x *AddKeysRequest) GetData() []*KeyInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeysResponse) Reset() {
	*x = AddKeysResponse{}
	mi := &file_api_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeysResponse) ProtoMessage() {}

func (x *AddKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeysResponse.ProtoReflect.Descriptor instead.
func (*AddKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{9}
}

type GetKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []string               `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeysRequest) Reset() {
	*x = GetKeysRequest{}
	mi := &file_api_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysRequest) ProtoMessage() {}

func (x *GetKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysRequest.ProtoReflect.Descriptor instead.
func (*GetKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeysRequest) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type GetKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*KeyInfo             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeysResponse) Reset() {
	*x = GetKeysResponse{}
	mi := &file_api_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysResponse) ProtoMessage() {}

func (x *GetKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysResponse.ProtoReflect.Descriptor instead.
func (*GetKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_search_proto_rawDescGZIP(), []int{11}
}

func (x *GetKeysResponse) GetResults() []*KeyInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_search_proto protoreflect.FileDescriptor

const file_api_search_proto_rawDesc = "" +
	"\n" +
	"\x10api/search.proto\x12\x10google.search.v1\"\x97\x06\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06c2coff\x18\x01 \x01(\tR\x06c2coff\x12\x0e\n" +
	"\x02cr\x18\x02 \x01(\tR\x02cr\x12#\n" +
	"\rdate_restrict\x18\x03 \x01(\tR\fdateRestrict\x12\x1f\n" +
	"\vexact_terms\x18\x04 \x01(\tR\n" +
	"exactTerms\x12#\n" +
	"\rexclude_terms\x18\x05 \x01(\tR\fexcludeTerms\x12\x1b\n" +
	"\tfile_type\x18\x06 \x01(\tR\bfileType\x12\x16\n" +
	"\x06filter\x18\a \x01(\tR\x06filter\x12\x0e\n" +
	"\x02gl\x18\b \x01(\tR\x02gl\x12\x1d\n" +
	"\n" +
	"high_range\x18\t \x01(\tR\thighRange\x12\x0e\n" +
	"\x02hl\x18\n" +
	" \x01(\tR\x02hl\x12\x0e\n" +
	"\x02hq\x18\v \x01(\tR\x02hq\x12$\n" +
	"\x0eimg_color_type\x18\f \x01(\tR\fimgColorType\x12,\n" +
	"\x12img_dominant_color\x18\r \x01(\tR\x10imgDominantColor\x12\x19\n" +
	"\bimg_size\x18\x0e \x01(\tR\aimgSize\x12\x19\n" +
	"\bimg_type\x18\x0f \x01(\tR\aimgType\x12\x1a\n" +
	"\blanguage\x18\x10 \x01(\tR\blanguage\x12\x1b\n" +
	"\tlink_site\x18\x11 \x01(\tR\blinkSite\x12\x1b\n" +
	"\tlow_range\x18\x12 \x01(\tR\blowRange\x12\x0e\n" +
	"\x02lr\x18\x13 \x01(\tR\x02lr\x12\x10\n" +
	"\x03num\x18\x14 \x01(\x05R\x03num\x12\x19\n" +
	"\bor_terms\x18\x15 \x01(\tR\aorTerms\x12\f\n" +
	"\x01q\x18\x16 \x01(\tR\x01q\x12\x16\n" +
	"\x06rights\x18\x17 \x01(\tR\x06rights\x12\x12\n" +
	"\x04safe\x18\x18 \x01(\tR\x04safe\x12\x1f\n" +
	"\vsearch_type\x18\x19 \x01(\tR\n" +
	"searchType\x12\x1f\n" +
	"\vsite_search\x18\x1a \x01(\tR\n" +
	"siteSearch\x12,\n" +
	"\x12site_search_filter\x18\x1b \x01(\tR\x10siteSearchFilter\x12\x12\n" +
	"\x04sort\x18\x1c \x01(\tR\x04sort\x12\x14\n" +
	"\x05start\x18\x1d \x01(\x05R\x05start\"R\n" +
	"\fSearchResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"J\n" +
	"\x0eSearchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.google.search.v1.SearchResultR\aresults\"U\n" +
	"\x15DeactivateKeysRequest\x12\x19\n" +
	"\bapi_keys\x18\x01 \x03(\tR\aapiKeys\x12!\n" +
	"\fforce_delete\x18\x02 \x01(\bR\vforceDelete\"\x18\n" +
	"\x16DeactivateKeysResponse\"0\n" +
	"\x13ActivateKeysRequest\x12\x19\n" +
	"\bapi_keys\x18\x01 \x03(\tR\aapiKeys\"\x16\n" +
	"\x14ActivateKeysResponse\"\xae\x02\n" +
	"\aKeyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12(\n" +
	"\x10search_engine_id\x18\x04 \x01(\tR\x0esearchEngineId\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12#\n" +
	"\rdaily_queries\x18\x06 \x01(\x05R\fdailyQueries\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x1b\n" +
	"\terror_msg\x18\b \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"?\n" +
	"\x0eAddKeysRequest\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.google.search.v1.KeyInfoR\x04data\"\x11\n" +
	"\x0fAddKeysResponse\"+\n" +
	"\x0eGetKeysRequest\x12\x19\n" +
	"\bapi_keys\x18\x01 \x03(\tR\aapiKeys\"F\n" +
	"\x0fGetKeysResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.google.search.v1.KeyInfoR\aresults2\xc0\x03\n" +
	"\rSearchService\x12K\n" +
	"\x06Search\x12\x1f.google.search.v1.SearchRequest\x1a .google.search.v1.SearchResponse\x12c\n" +
	"\x0eDeactivateKeys\x12'.google.search.v1.DeactivateKeysRequest\x1a(.google.search.v1.DeactivateKeysResponse\x12]\n" +
	"\fActivateKeys\x12%.google.search.v1.ActivateKeysRequest\x1a&.google.search.v1.ActivateKeysResponse\x12N\n" +
	"\aAddKeys\x12 .google.search.v1.AddKeysRequest\x1a!.google.search.v1.AddKeysResponse\x12N\n" +
	"\aGetKeys\x12 .google.search.v1.GetKeysRequest\x1a!.google.search.v1.GetKeysResponseB\x0fZ\rpkg/searchsvcb\x06proto3"

var (
	file_api_search_proto_rawDescOnce sync.Once
	file_api_search_proto_rawDescData []byte
)

func file_api_search_proto_rawDescGZIP() []byte {
	file_api_search_proto_rawDescOnce.Do(func() {
		file_api_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_search_proto_rawDesc), len(file_api_search_proto_rawDesc)))
	})
	return file_api_search_proto_rawDescData
}

var file_api_search_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_search_proto_goTypes = []any{
	(*SearchRequest)(nil),          // 0: google.search.v1.SearchRequest
	(*SearchResult)(nil),           // 1: google.search.v1.SearchResult
	(*SearchResponse)(nil),         // 2: google.search.v1.SearchResponse
	(*DeactivateKeysRequest)(nil),  // 3: google.search.v1.DeactivateKeysRequest
	(*DeactivateKeysResponse)(nil), // 4: google.search.v1.DeactivateKeysResponse
	(*ActivateKeysRequest)(nil),    // 5: google.search.v1.ActivateKeysRequest
	(*ActivateKeysResponse)(nil),   // 6: google.search.v1.ActivateKeysResponse
	(*KeyInfo)(nil),                // 7: google.search.v1.KeyInfo
	(*AddKeysRequest)(nil),         // 8: google.search.v1.AddKeysRequest
	(*AddKeysResponse)(nil),        // 9: google.search.v1.AddKeysResponse
	(*GetKeysRequest)(nil),         // 10: google.search.v1.GetKeysRequest
	(*GetKeysResponse)(nil),        // 11: google.search.v1.GetKeysResponse
}
var file_api_search_proto_depIdxs = []int32{
	1,  // 0: google.search.v1.SearchResponse.results:type_name -> google.search.v1.SearchResult
	7,  // 1: google.search.v1.AddKeysRequest.data:type_name -> google.search.v1.KeyInfo
	7,  // 2: google.search.v1.GetKeysResponse.results:type_name -> google.search.v1.KeyInfo
	0,  // 3: google.search.v1.SearchService.Search:input_type -> google.search.v1.SearchRequest
	3,  // 4: google.search.v1.SearchService.DeactivateKeys:input_type -> google.search.v1.DeactivateKeysRequest
	5,  // 5: google.search.v1.SearchService.ActivateKeys:input_type -> google.search.v1.ActivateKeysRequest
	8,  // 6: google.search.v1.SearchService.AddKeys:input_type -> google.search.v1.AddKeysRequest
	10, // 7: google.search.v1.SearchService.GetKeys:input_type -> google.search.v1.GetKeysRequest
	2,  // 8: google.search.v1.SearchService.Search:output_type -> google.search.v1.SearchResponse
	4,  // 9: google.search.v1.SearchService.DeactivateKeys:output_type -> google.search.v1.DeactivateKeysResponse
	6,  // 10: google.search.v1.SearchService.ActivateKeys:output_type -> google.search.v1.ActivateKeysResponse
	9,  // 11: google.search.v1.SearchService.AddKeys:output_type -> google.search.v1.AddKeysResponse
	11, // 12: google.search.v1.SearchService.GetKeys:output_type -> google.search.v1.GetKeysResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_search_proto_init() }
func file_api_search_proto_init() {
	if File_api_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_search_proto_rawDesc), len(file_api_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_search_proto_goTypes,
		DependencyIndexes: file_api_search_proto_depIdxs,
		MessageInfos:      file_api_search_proto_msgTypes,
	}.Build()
	File_api_search_proto = out.File
	file_api_search_proto_goTypes = nil
	file_api_search_proto_depIdxs = nil
}
