name: Build and deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "master"

permissions:
  contents: write
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # build with tag master if from push event or with tag as input version
          export tag=${{ github.event.inputs.version || 'master' }}
          docker build -t findx:$tag .
          docker tag findx:$tag ghcr.io/taquangtu/findx:$tag
          docker push ghcr.io/taquangtu/findx:$tag

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Redeploy on SSH server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_HOSTINGER }}
          username: ${{ secrets.USERNAME_HOSTINGER }}
          key: ${{ secrets.KEY_HOSTINGER }}
          port: ${{ secrets.PORT_HOSTINGER }}
          script: |
            export tag=${{ github.event.inputs.version || 'master' }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            mkdir -p "findx/${{ github.ref_name }}"
            cd "findx/${{ github.ref_name }}"
            docker pull ghcr.io/taquangtu/findx:$tag
            docker compose up -d --force-recreate
