name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Install pre-commit
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pre-commit

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          golangci-lint --version

      - name: Cache pre-commit hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run YAML checks
        run: pre-commit run check-yaml --all-files

      - name: Run end-of-file-fixer
        run: pre-commit run end-of-file-fixer --all-files

      - name: Run trailing-whitespace
        run: pre-commit run trailing-whitespace --all-files

      - name: Run check-added-large-files
        run: pre-commit run check-added-large-files --all-files

      - name: Run requirements-txt-fixer
        run: pre-commit run requirements-txt-fixer --all-files

      - name: Run check-merge-conflict
        run: pre-commit run check-merge-conflict --all-files

      - name: Run debug-statements
        run: pre-commit run debug-statements --all-files

      - name: Run pretty-format-json
        run: pre-commit run pretty-format-json --all-files

      - name: Run go-fmt
        run: pre-commit run go-fmt --all-files

      - name: Run go-mod-tidy
        run: pre-commit run go-mod-tidy --all-files

      - name: Run golangci-lint
        run: pre-commit run golangci-lint --all-files

      - name: Run hadolint-docker
        run: pre-commit run hadolint-docker --all-files

      - name: Run go vet
        run: go vet ./...

  build:
    runs-on: ubuntu-latest
    needs: pre-commit-checks
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
